services:
  prometheus:
    image: prom/prometheus:latest
    user: root # ew!!!!!!
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
