/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BotMovementLedger {
  bot_id: Int8;
  created_at: Timestamp | null;
  id: Generated<Int8>;
  new_x: Numeric;
  new_y: Numeric;
  time_action_started: Timestamp;
  updated_at: Timestamp | null;
  user_id: Int8;
}

export interface Bots {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  identifier: string;
  inventory_count: number;
  name: string;
  updated_at: Timestamp | null;
  user_id: Int8;
}

export interface HttpSessions {
  created_on: Generated<Timestamp | null>;
  data: Buffer | null;
  expires_on: Timestamp | null;
  id: Generated<Int8>;
  key: Buffer | null;
  modified_on: Timestamp | null;
}

export interface Mines {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  updated_at: Timestamp | null;
  user_id: Int8;
  x: Numeric;
  y: Numeric;
}

export interface Users {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  password: string;
  updated_at: Timestamp | null;
  username: string;
}

export interface DB {
  bot_movement_ledger: BotMovementLedger;
  bots: Bots;
  http_sessions: HttpSessions;
  mines: Mines;
  users: Users;
}
