//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Bots struct {
	ID             int64 `sql:"primary_key"`
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	UserID         int64
	Identifier     string
	InventoryCount int16
	Name           string
}
